// Generated by script/fetchTokenMetadata.ts

export const tokenMetadata = {
  address: "0x1B85deDe8178E18CdE599B4C9d913534553C3dBf",
  decimals: 6,
  symbol: "USDC",
  name: "testUSDC",
  totalSupply: "1000000000000",
} as const;
