// Generated by script/fetchTokenMetadata.ts

export const tokenMetadata = {
  address: "0xdFa757C73F1fBd01471f292A9137238254e36655",
  decimals: 6,
  symbol: "USDC",
  name: "testUSDC",
  totalSupply: "1000000000000",
} as const;
