// Generated by script/fetchTokenMetadata.ts

export const tokenMetadata = {
  "8453": {
    address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    decimals: 6,
    symbol: "USDC",
    name: "USD Coin",
    chainId: 8453,
    paymasterAddress: "0x939263eafe57038a072cb4edd6b25dd81a8a6c56",
  },
  "84531": {
    address: "0x1B85deDe8178E18CdE599B4C9d913534553C3dBf",
    decimals: 6,
    symbol: "USDC",
    name: "testUSDC",
    chainId: 84531,
    paymasterAddress: "0x13f490FafBb206440F25760A10C21A6220017fFa",
  },
} as const;
