// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	ACCEPT_LINK: {
		/**
		 * A​c​c​e​p​t​ ​l​i​n​k
		 */
		title: string
		/**
		 * A​c​c​e​p​t​ ​t​h​i​s​ ​l​i​n​k​,​ ​r​e​c​e​i​v​i​n​g​ 
		 */
		description: string
	}
	/**
	 * C​a​n​c​e​l​ ​t​h​i​s​ ​l​i​n​k​,​ ​r​e​c​l​a​i​m​i​n​g​ 
	 */
	CANCEL_LINK: string
	/**
	 * G​a​s​ ​t​o​o​ ​h​i​g​h​ ​t​o​ ​c​l​a​i​m
	 */
	GAS_TOO_HIGH_LINK: string
	/**
	 * A​c​c​e​p​t​e​d​ ​L​i​n​k
	 */
	CLAIMED_LINK: string
	/**
	 * C​a​n​c​e​l​l​e​d​ ​L​i​n​k
	 */
	CANCELLED_LINK: string
	/**
	 * P​a​y​m​e​n​t​ ​L​i​n​k
	 */
	PAYMENT_LINK: string
	/**
	 * P​a​y​m​e​n​t​ ​l​i​n​k​ ​i​n​v​a​l​i​d
	 */
	INVALID_LINK: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	SETTINGS: string
}

export type TranslationFunctions = {
	ACCEPT_LINK: {
		/**
		 * Accept link
		 */
		title: () => LocalizedString
		/**
		 * Accept this link, receiving 
		 */
		description: () => LocalizedString
	}
	/**
	 * Cancel this link, reclaiming 
	 */
	CANCEL_LINK: () => LocalizedString
	/**
	 * Gas too high to claim
	 */
	GAS_TOO_HIGH_LINK: () => LocalizedString
	/**
	 * Accepted Link
	 */
	CLAIMED_LINK: () => LocalizedString
	/**
	 * Cancelled Link
	 */
	CANCELLED_LINK: () => LocalizedString
	/**
	 * Payment Link
	 */
	PAYMENT_LINK: () => LocalizedString
	/**
	 * Payment link invalid
	 */
	INVALID_LINK: () => LocalizedString
	/**
	 * Settings
	 */
	SETTINGS: () => LocalizedString
}

export type Formatters = {}
