import * as fs from "fs";
import { createPublicClient, getContract, http } from "viem";
import { baseGoerli } from "viem/chains";

import * as Contracts from "../src/generated";

async function main() {
  const publicClient = createPublicClient({
    chain: baseGoerli,
    transport: http(),
  });

  const erc20 = getContract({
    abi: Contracts.erc20ABI,
    address: Contracts.testUsdcAddress,
    publicClient,
  });

  console.log("✔ Fetching erc20 metadata");
  const tokenDecimals = await erc20.read.decimals();
  const tokenSymbol = await erc20.read.symbol();
  const tokenName = await erc20.read.name();
  const tokenSupply = await erc20.read.totalSupply();

  const fileStr = `// Generated by script/fetchTokenMetadata.ts

export const tokenMetadata = {
  address: "${Contracts.testUsdcAddress}",
  decimals: ${tokenDecimals},
  symbol: "${tokenSymbol}",
  name: "${tokenName}",
  totalSupply: "${tokenSupply}",
} as const;
`;

  console.log("✔ Writing to src/tokenMetadata.ts");
  fs.writeFileSync("./src/tokenMetadata.ts", fileStr);
}

main();
