import * as fs from "fs";
import { createPublicClient, getContract, http } from "viem";
import { baseGoerli } from "viem/chains";

import * as Contracts from "../src/generated";

const abi = Contracts.erc20ABI;

// This one spot is the only place where Daimo's stablecoin is hardcoded.
// Everything else is generated from the contract.

// Base Goerli testUSDC
const address = "0x1B85deDe8178E18CdE599B4C9d913534553C3dBf";

async function main() {
  const publicClient = createPublicClient({
    chain: baseGoerli,
    transport: http(),
  });

  const erc20 = getContract({ abi, address, publicClient });

  console.log("✔ Fetching erc20 metadata");
  const tokenDecimals = await erc20.read.decimals();
  const tokenSymbol = await erc20.read.symbol();
  const tokenName = await erc20.read.name();
  // No totalSupply, since that's mutable.

  const fileStr = `// Generated by script/fetchTokenMetadata.ts

export const tokenMetadata = {
  address: "${address}",
  decimals: ${tokenDecimals},
  symbol: "${tokenSymbol}",
  name: "${tokenName}"
} as const;
`;

  console.log("✔ Writing to src/tokenMetadata.ts");
  fs.writeFileSync("./src/tokenMetadata.ts", fileStr);
}

main();
