[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]

# Compiler settings
solc = "0.8.21"
optimizer = true
optimizer_runs = 999_999

# See more config options https://github.com/foundry-rs/foundry/tree/master/config