[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Compiler settings
solc = "0.8.21"
via-ir = true
optimizer = true
optimizer_runs = 999_999

# See more config options https://github.com/foundry-rs/foundry/tree/master/config