name: Maestro CI

on:
  push:
    branches: [disabled] # [master], Maestro CI is currently failing

jobs:
  maestro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          packager: npm
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Wait for iOS and Android expo builds to start
        run: sleep 120

      - name: Run Maestro test suite
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          RUN_ID: ${{ github.event.number || github.run_id }}
        run: |
          echo "BRANCH_NAME=${BRANCH_NAME}" >> .env.maestro
          echo "RUN_ID=${RUN_ID}" >> .env.maestro
          npm run build:maestro
        working-directory: ./apps/daimo-mobile
